-- Suppression des tables
DROP TABLE IF EXISTS PLAYLIST;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS ALBUM_GENRE;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS ARTISTE;
DROP TABLE IF EXISTS CHANSON;
DROP TABLE IF EXISTS IMAGE_ARTISTE

